# Generated by Django 4.2.2 on 2024-04-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('business_categories', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
                ('age_of_business', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
