# Generated by Django 4.2.2 on 2024-04-28 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_age_of_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='age_of_business',
            new_name='age_of_business_in_days',
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
