# Generated by Django 4.2.2 on 2024-04-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_age_of_business_customer_age_of_business_in_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age_of_business_in_days',
        ),
    ]
