# Generated by Django 4.2.2 on 2024-04-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_customer_age_of_business_in_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='business_categories',
            new_name='business_category',
        ),
    ]
